//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class blogQuoteAuthor
    {
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public int ApplicationID { get; set; }
        public int QuoteAuthorID { get; set; }
        public Nullable<int> AuthorTypeID { get; set; }
        public string AuthorFullName { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public Nullable<int> FamousForID { get; set; }
        public string Nationality { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateDied { get; set; }
        public string DataUsed { get; set; }
        public System.DateTime EntryDate { get; set; }
        public System.Guid EntryUserID { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<System.Guid> LastUpdateUserID { get; set; }
    }
}
