//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapERP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbERPSolutionEntities : DbContext
    {
        public dbERPSolutionEntities()
            : base("name=dbERPSolutionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<uUserProfileTemp> uUserProfileTemps { get; set; }
        public virtual DbSet<EmployeeTitle> EmployeeTitles { get; set; }
        public virtual DbSet<tblStartLearning> tblStartLearnings { get; set; }
        public virtual DbSet<lrnCourseCategory> lrnCourseCategories { get; set; }
        public virtual DbSet<lrnCourseContentType> lrnCourseContentTypes { get; set; }
        public virtual DbSet<lrnCourseType> lrnCourseTypes { get; set; }
        public virtual DbSet<lrnLearningPath> lrnLearningPaths { get; set; }
        public virtual DbSet<lrnProviderName> lrnProviderNames { get; set; }
        public virtual DbSet<lrnCourseLevel> lrnCourseLevels { get; set; }
        public virtual DbSet<siteApplicationSetup> siteApplicationSetups { get; set; }
        public virtual DbSet<siteContentCategory> siteContentCategories { get; set; }
        public virtual DbSet<siteContentRelatedTo> siteContentRelatedToes { get; set; }
        public virtual DbSet<siteContentType> siteContentTypes { get; set; }
        public virtual DbSet<SiteContentRecord> SiteContentRecords { get; set; }
        public virtual DbSet<siteContentEntryTemp> siteContentEntryTemps { get; set; }
        public virtual DbSet<blogContentCategory> blogContentCategories { get; set; }
        public virtual DbSet<blogContentRelatedTo> blogContentRelatedToes { get; set; }
        public virtual DbSet<blogActionType> blogActionTypes { get; set; }
        public virtual DbSet<uRoleTypeSetup> uRoleTypeSetups { get; set; }
        public virtual DbSet<suDefaultNodeList> suDefaultNodeLists { get; set; }
        public virtual DbSet<uDefaultNodeList> uDefaultNodeLists { get; set; }
        public virtual DbSet<uNodePosition> uNodePositions { get; set; }
        public virtual DbSet<uNodeType> uNodeTypes { get; set; }
        public virtual DbSet<uRoleSetup> uRoleSetups { get; set; }
        public virtual DbSet<uUserTypeSetup> uUserTypeSetups { get; set; }
        public virtual DbSet<blogAuthorTypeSetup> blogAuthorTypeSetups { get; set; }
        public virtual DbSet<blogFamousForSetup> blogFamousForSetups { get; set; }
        public virtual DbSet<DataUsedSetup> DataUsedSetups { get; set; }
        public virtual DbSet<GenderSetup> GenderSetups { get; set; }
        public virtual DbSet<MaritalStatusSetup> MaritalStatusSetups { get; set; }
        public virtual DbSet<orgBranch> orgBranches { get; set; }
        public virtual DbSet<orgDepartment> orgDepartments { get; set; }
        public virtual DbSet<orgSection> orgSections { get; set; }
        public virtual DbSet<orgTeam> orgTeams { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<ReligionSetup> ReligionSetups { get; set; }
        public virtual DbSet<RoleTypeSetup> RoleTypeSetups { get; set; }
        public virtual DbSet<ServiceCategoryType> ServiceCategoryTypes { get; set; }
        public virtual DbSet<blogQuoteAuthor> blogQuoteAuthors { get; set; }
        public virtual DbSet<BrowserNameSetup> BrowserNameSetups { get; set; }
        public virtual DbSet<CountryNameSetup> CountryNameSetups { get; set; }
        public virtual DbSet<DeviceTypeSetup> DeviceTypeSetups { get; set; }
        public virtual DbSet<AllUser> AllUsers { get; set; }
        public virtual DbSet<MessageEmailCategory> MessageEmailCategories { get; set; }
        public virtual DbSet<MessageEmailSubCategory> MessageEmailSubCategories { get; set; }
        public virtual DbSet<MessageEmailType> MessageEmailTypes { get; set; }
        public virtual DbSet<MessageEmailActionType> MessageEmailActionTypes { get; set; }
        public virtual DbSet<orgDesignation> orgDesignations { get; set; }
        public virtual DbSet<BusinessNatureSetup> BusinessNatureSetups { get; set; }
        public virtual DbSet<DistrictSetupView> DistrictSetupViews { get; set; }
        public virtual DbSet<OwnershipSetup> OwnershipSetups { get; set; }
    
        public virtual int spInitiateSecurityCode(Nullable<System.Guid> userProfileID, Nullable<System.Guid> entryUserID, Nullable<int> securityCode)
        {
            var userProfileIDParameter = userProfileID.HasValue ?
                new ObjectParameter("UserProfileID", userProfileID) :
                new ObjectParameter("UserProfileID", typeof(System.Guid));
    
            var entryUserIDParameter = entryUserID.HasValue ?
                new ObjectParameter("EntryUserID", entryUserID) :
                new ObjectParameter("EntryUserID", typeof(System.Guid));
    
            var securityCodeParameter = securityCode.HasValue ?
                new ObjectParameter("SecurityCode", securityCode) :
                new ObjectParameter("SecurityCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInitiateSecurityCode", userProfileIDParameter, entryUserIDParameter, securityCodeParameter);
        }
    
        public virtual int spInitiateSecurityCodeForgotPassword(Nullable<System.Guid> userProfileID, Nullable<System.Guid> entryUserID, Nullable<int> securityCode)
        {
            var userProfileIDParameter = userProfileID.HasValue ?
                new ObjectParameter("UserProfileID", userProfileID) :
                new ObjectParameter("UserProfileID", typeof(System.Guid));
    
            var entryUserIDParameter = entryUserID.HasValue ?
                new ObjectParameter("EntryUserID", entryUserID) :
                new ObjectParameter("EntryUserID", typeof(System.Guid));
    
            var securityCodeParameter = securityCode.HasValue ?
                new ObjectParameter("SecurityCode", securityCode) :
                new ObjectParameter("SecurityCode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInitiateSecurityCodeForgotPassword", userProfileIDParameter, entryUserIDParameter, securityCodeParameter);
        }
    }
}
