//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceTypeSetup
    {
        public string DeviceType { get; set; }
        public string DeviceTypeID { get; set; }
        public System.Guid LoginInfoID { get; set; }
        public System.Guid SessionID { get; set; }
    }
}
