//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageEmailSubCategory
    {
        public int MessageCategoryID { get; set; }
        public int MessageSubCategoryID { get; set; }
        public string MessageSubCategoryTitle { get; set; }
        public string DataUsed { get; set; }
        public System.DateTime EntryDate { get; set; }
        public System.Guid EntryUserID { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<System.Guid> LastUpdateUserID { get; set; }
    }
}
