//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orgDepartment
    {
        public byte CompanyID { get; set; }
        public int ParentEntityID { get; set; }
        public int EntityID { get; set; }
        public string AddressTag { get; set; }
        public Nullable<int> AddressID { get; set; }
        public string EntityName { get; set; }
        public string ShortName { get; set; }
        public string DisplayName { get; set; }
        public string GroupEmailAddress { get; set; }
        public string HeadID { get; set; }
        public string EntityCategoryID { get; set; }
        public Nullable<System.DateTime> EntityOpeningDate { get; set; }
        public string DataUsed { get; set; }
        public System.Guid EntryUserID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<System.Guid> LastUpdateUserID { get; set; }
    }
}
