//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteContentRecord
    {
        public int ContentID { get; set; }
        public string ApplicationTitle { get; set; }
        public string ContentTypeDescription { get; set; }
        public string ContentCategoryTitle { get; set; }
        public string ContentTitle { get; set; }
        public System.Guid EntryUserID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
    }
}
