//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siteContentEntryTemp
    {
        public int contentID { get; set; }
        public string contentTitle { get; set; }
        public byte[] contentImage { get; set; }
        public string contentImageURL { get; set; }
        public string contentDescription { get; set; }
        public string DataUsed { get; set; }
        public string contentRemarks { get; set; }
        public Nullable<System.Guid> EntryUserID { get; set; }
        public Nullable<int> contentParentID { get; set; }
        public string contentSubTitle { get; set; }
        public string introductoryText { get; set; }
    }
}
