//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siteContentCategory
    {
        public int ContentCategoryID { get; set; }
        public Nullable<int> ContentTypeID { get; set; }
        public string ContentCategoryTitle { get; set; }
        public string ContentCategoryDescription { get; set; }
        public string ContentCategoryImage { get; set; }
        public Nullable<int> ContentRelatedToID { get; set; }
        public string DataUsed { get; set; }
        public System.DateTime EntryDate { get; set; }
        public System.Guid EntryUserID { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<System.Guid> LastUpdateUserID { get; set; }
    }
}
