//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStartLearning
    {
        public int NodeTypeID { get; set; }
        public int PNodeTypeID { get; set; }
        public string ActivityName { get; set; }
        public string Description { get; set; }
    }
}
