//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uDefaultNodeList
    {
        public int CompanyID { get; set; }
        public int BranchID { get; set; }
        public int ActivityID { get; set; }
        public string ActivityName { get; set; }
        public int SeqNo { get; set; }
        public int NodeTypeID { get; set; }
        public int PNodeTypeID { get; set; }
        public string ControllerTitle { get; set; }
        public string ActionTitle { get; set; }
        public string FormDescription { get; set; }
        public string FormName { get; set; }
        public Nullable<int> ShowPosition { get; set; }
        public string DataUsed { get; set; }
        public Nullable<System.Guid> EntryUserID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<System.Guid> LastUpdateUserID { get; set; }
        public string UserID { get; set; }
        public string NodeCheckValue { get; set; }
    }
}
