//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootstrapERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uUserProfileTemp
    {
        public System.Guid UserProfileID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyEmail { get; set; }
        public string UserEmail { get; set; }
        public string UserTitle { get; set; }
        public string UserName { get; set; }
        public string DataUsed { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string MobileNumber { get; set; }
        public string LastName { get; set; }
    }
}
